services:
  teleop:
    build:
      context: .
      dockerfile: Dockerfile.humble
      args:
        ROS_DISTRO: ${ROS_DISTRO:-humble}
    image: ros2-${ROS_DISTRO:-humble}:foxglove
    container_name: ${ROS_DISTRO:-humble}
    network_mode: host
    stdin_open: true
    tty: true
    env_file:
      - ../common.env
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    # volumes:
    #   - ./entrypoint.sh:/entrypoint.sh
    #   - /tmp/.X11-unix:/tmp/.X11-unix:rw
    #   - ${HOME}/.Xauthority:/root/.Xauthority:ro
    # command: bash /entrypoint.sh