services:
  teleop:
    build:
      context: .
      dockerfile: Dockerfile.humble
    image: ros2-humble:foxglove
    container_name: ros2-humble
    network_mode: host
    stdin_open: true
    tty: true
    env_file:
      - ../common.env
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    command: bash /entrypoint.sh